# cluster.conf
# Configuration file for GKE cluster deployment

# The GCP Project ID where the cluster will be deployed
PROJECT_ID="your-gcp-project-id"

# The region where the cluster and bucket will be created
REGION="europe-west1"

# The zone for the H200 node pool
ZONE="europe-west1-b"

# Name of the GKE deployment
DEPLOYMENT_NAME="my-gke-cluster"

# The GCS Bucket to store Terraform state (without gs:// prefix)
# Choose a globally unique name
TF_STATE_BUCKET="my-unique-tf-state-bucket"

# The name of the specific compute engine reservation to consume
RESERVATION_NAME="my-h200-reservation"

# CIDR block containing the IP of the machine calling this script
# Set it to your specific IP to lock down master authorized networks
AUTHORIZED_CIDR="0.0.0.0/0"

# The number of accelerated (H200) nodes to provision
H200_NODE_COUNT="6"

# GCS Buckets for sample mistral 8x7B MoE model training
GCS_BUCKET="my-generic-test-bucket"
GCS_TRAINING_BUCKET="my-generic-training-bucket"
GCS_CHECKPOINT_BUCKET="my-generic-checkpoint-bucket"
