# cluster.conf
# Configuration file for GKE cluster deployment

# The GCP Project ID where the cluster will be deployed
PROJECT_ID="your-gcp-project-id"

# The region where the cluster and bucket will be created
REGION="europe-west1"

# The zone for the H200 node pool
ZONE="europe-west1-b"

# Name of the GKE deployment
DEPLOYMENT_NAME="my-gke-cluster"

# The name of the specific compute engine reservation to consume
RESERVATION_NAME="my-h200-reservation"

# The number of accelerated (H200) nodes to provision
H200_NODE_COUNT="6"

# GCS Buckets for sample mistral 8x7B MoE model training
GCS_BUCKET="my-generic-test-bucket"
GCS_TRAINING_BUCKET="my-generic-training-bucket"
GCS_CHECKPOINT_BUCKET="my-generic-checkpoint-bucket"
